### ISSUE TITLE
Float (Float32) columns are not being read correctly

### ISSUE THREAD

**Issue by tikkanz** [interregna/JArrow#6]
"FLOAT" columns are not being correctly read into J as floats.

If the column in the parquet file is converted to Double/Float64 using alternative software and re-saved as a new parquet file, then the "DOUBLE" is read correctly.

**Comment by interregna** [comment]
Do you know what datatype the alternative software is saving? That is, can you do:
`readSchemaString readParquet [your file path]`

It's possible that the alternative software was dumping float32, which was not read correctly in the FFI prior to the last commit. That has been corrected. Perhaps try this again as well.

**Comment by tikkanz** [comment]
Yep that looks great!
Fixed in c1a7c590b0a1c8b3dfdf07d7d57ad53e64b9c373
